# I - Imports

In [1]:
from selenium import webdriver
import pandas as pd
import time
import requests
import urllib.request
from bs4 import BeautifulSoup
import csv

# II - Récupération des URLS

### Récupération des urls des Ligues

In [2]:
League = ['Premier League', 'Serie A', 'La Liga','Bundesliga', 'Ligue1' ]

saison8=[
'https://www.whoscored.com/Regions/252/Tournaments/2/Seasons/6335/Stages/13796/TeamStatistics/England-Premier-League-2016-2017',
'https://www.whoscored.com/Regions/108/Tournaments/5/Seasons/6461/Stages/14014/TeamStatistics/Italy-Serie-A-2016-2017',
'https://www.whoscored.com/Regions/206/Tournaments/4/Seasons/6436/Stages/13955/TeamStatistics/Spain-LaLiga-2016-2017',
'https://www.whoscored.com/Regions/81/Tournaments/3/Seasons/6392/Stages/13872/TeamStatistics/Germany-Bundesliga-2016-2017',
'https://www.whoscored.com/Regions/74/Tournaments/22/Seasons/6318/Stages/13768/TeamStatistics/France-Ligue-1-2016-2017'    
        ]
saison9=[
'https://www.whoscored.com/Regions/252/Tournaments/2/Seasons/6829/Stages/15151/TeamStatistics/England-Premier-League-2017-2018',
'https://www.whoscored.com/Regions/108/Tournaments/5/Seasons/6974/Stages/15404/TeamStatistics/Italy-Serie-A-2017-2018',
'https://www.whoscored.com/Regions/206/Tournaments/4/Seasons/6960/Stages/15375/TeamStatistics/Spain-LaLiga-2017-2018',
'https://www.whoscored.com/Regions/81/Tournaments/3/Seasons/6902/Stages/15243/TeamStatistics/Germany-Bundesliga-2017-2018',
'https://www.whoscored.com/Regions/74/Tournaments/22/Seasons/6833/Stages/15155/TeamStatistics/France-Ligue-1-2017-2018'    
]
saison10=[
'https://www.whoscored.com/Regions/252/Tournaments/2/Seasons/7361/Stages/16368/TeamStatistics/England-Premier-League-2018-2019',
'https://www.whoscored.com/Regions/108/Tournaments/5/Seasons/7468/Stages/16548/TeamStatistics/Italy-Serie-A-2018-2019',
'https://www.whoscored.com/Regions/206/Tournaments/4/Seasons/7466/Stages/16546/TeamStatistics/Spain-LaLiga-2018-2019',
'https://www.whoscored.com/Regions/81/Tournaments/3/Seasons/7405/Stages/16427/TeamStatistics/Germany-Bundesliga-2018-2019',
'https://www.whoscored.com/Regions/74/Tournaments/22/Seasons/7344/Stages/16348/TeamStatistics/France-Ligue-1-2018-2019'    
]

df_url = pd.DataFrame(
{
    "League" : League, 
    #"2009-2010" : saison1,
    #"2010-2011" : saison2,
    #"2011-2012" : saison3,
    #"2012-2013" : saison4,
    #"2013-2014" : saison5,
    #"2014-2015" : saison6,
    #"2015-2016" : saison7,
    "2016-2017" : saison8,
    "2017-2018" : saison9,
    "2018-2019" : saison10,
}
)

df_url

,League,2016-2017,2017-2018,2018-2019
0,Premier League,https://www.whoscored.com/Regions/252/Tourname...,https://www.whoscored.com/Regions/252/Tourname...,https://www.whoscored.com/Regions/252/Tourname...
1,Serie A,https://www.whoscored.com/Regions/108/Tourname...,https://www.whoscored.com/Regions/108/Tourname...,https://www.whoscored.com/Regions/108/Tourname...
2,La Liga,https://www.whoscored.com/Regions/206/Tourname...,https://www.whoscored.com/Regions/206/Tourname...,https://www.whoscored.com/Regions/206/Tourname...
3,Bundesliga,https://www.whoscored.com/Regions/81/Tournamen...,https://www.whoscored.com/Regions/81/Tournamen...,https://www.whoscored.com/Regions/81/Tournamen...
4,Ligue1,https://www.whoscored.com/Regions/74/Tournamen...,https://www.whoscored.com/Regions/74/Tournamen...,https://www.whoscored.com/Regions/74/Tournamen...

In [385]:
years = ['2018-2019','2017-2018','2016-2017']

,League,2016-2017,2017-2018,2018-2019
0,Premier League,https://www.whoscored.com/Regions/252/Tourname...,https://www.whoscored.com/Regions/252/Tourname...,https://www.whoscored.com/Regions/252/Tourname...
1,Serie A,https://www.whoscored.com/Regions/108/Tourname...,https://www.whoscored.com/Regions/108/Tourname...,https://www.whoscored.com/Regions/108/Tourname...
2,La Liga,https://www.whoscored.com/Regions/206/Tourname...,https://www.whoscored.com/Regions/206/Tourname...,https://www.whoscored.com/Regions/206/Tourname...
3,Bundesliga,https://www.whoscored.com/Regions/81/Tournamen...,https://www.whoscored.com/Regions/81/Tournamen...,https://www.whoscored.com/Regions/81/Tournamen...
4,Ligue1,https://www.whoscored.com/Regions/74/Tournamen...,https://www.whoscored.com/Regions/74/Tournamen...,https://www.whoscored.com/Regions/74/Tournamen...

In [327]:
url = df_url['2018-2019'][0]
driver = webdriver.Chrome()
driver.get(url)

# Definition des parsers

In [261]:
def parse_glob(n,teams,parameters,table,button="None"):
    headers_table = []
    final_results = []
    
    #print(button)
    
    if button!="None":
        
        button_to_click =driver.find_elements_by_xpath(button)[0]
        button_to_click.click()
    
        time.sleep(1)
    
    rows = driver.find_elements_by_css_selector(table)

#Recuperation des headers
    for row in rows:
        temp = []
        columns = row.find_elements_by_css_selector("th")

        for column in columns:
            temp.append(column.text)
        headers_table.append(temp)
    
#Recuperation des results:

    rows = driver.find_elements_by_css_selector(table)
    results_table = []
        
    for row in rows:
        temp = []
        columns = row.find_elements_by_css_selector("td")

        for column in columns:
            temp.append(column.text)
        results_table.append(temp)
        
        results_table_final=[results_table[0][i*parameters:parameters*(i+1)] for i in range(teams)]
        
        final_results += results_table_final
        
    return headers_table,final_results

# Selection de la table Summary

In [187]:
nb_de_pages=1

In [272]:
headers, table_t = parse_glob(nb_de_pages,teams=20,parameters=9,table="#top-team-stats-summary-grid")

In [299]:
df_summanry = pd.DataFrame(table_t, columns=headers[0][:8])
df_summanry

,R,Team,Shots pg,Tackles pg,Interceptions pg,Fouls pg,Offsides pg,Rating
0,1,Manchester City,6.3,13.7,9.5,8.6,2.6,7.09
1,2,Liverpool,8.1,16.1,8.3,8.3,2,7.01
2,3,Chelsea,9.2,16.3,9.3,8.9,2.2,6.89
3,4,Tottenham,12.1,16.5,8.6,9.9,1.9,6.86
4,5,Arsenal,13.1,16,10.8,10.8,2.3,6.79
5,6,Leicester,11.2,17.8,11.5,9.2,1.9,6.78
6,7,Crystal Palace,13.8,19.3,11.7,10.2,2.1,6.78
7,8,West Ham,13.9,19,12,8.7,1.9,6.77
8,9,Everton,10.6,18.4,11.9,11.4,1.8,6.77
9,10,Wolverhampton Wanderers,12.2,18.9,13.2,10.8,1.9,6.75
10,11,Newcastle United,12.9,18.8,13.3,11.1,1.6,6.74
11,12,Manchester United,13.1,15.3,9.3,11.4,2.4,6.74
12,13,Burnley,17.2,15.4,9.7,9.5,2.8,6.70
13,14,Southampton,13.7,18.4,14.4,11.1,1.6,6.68
14,15,Watford,12.9,17.3,11.3,11.4,2.3,6.68
15,16,Bournemouth,13.7,13.8,9.8,8.9,1.5,6.68
16,17,Cardiff,15,17.2,13.9,9.8,2,6.62
17,18,Brighton,15.3,17.9,12.2,12.2,2.4,6.61
18,19,Fulham,15.4,15.7,11.3,11.1,2.4,6.56
19,20,Huddersfield,13.7,18.6,14,11.1,1.7,6.47

# Selection de la table Defensive

In [279]:
headers, table_t = parse_glob(nb_de_pages,
                              teams=20,
                              parameters=8,
                              table="#stage-team-stats-defensive",
                              button='//*[@id="stage-team-stats-options"]/li[2]/a')

In [308]:
df_defensive = pd.DataFrame(table_t, columns=headers[0][:8])
df_defensive
df_defensive.columns = ['R', 'Team', 'Shots conceded pg', 'Tackles pg', 'Interceptions pg', 'Fouls pg',
       'Offsides pg', 'Rating']
df_defensive = df_defensive.drop('Rating',axis=1)

 - Shots pg: Shots conceded per game	
 - Tackles pg: Tackles per game	
 - Interceptions pg: Interceptions per game
 - Fouls pg: Fouls per game
 - Offsides pg: Offsides per game

# Selection de la table Offensive

In [310]:
headers, table_t = parse_glob(nb_de_pages,
                              teams=20,
                              parameters=7,
                              table="#stage-team-stats-offensive",
                              button='//*[@id="stage-team-stats-options"]/li[3]/a')

In [311]:
df_offensive = pd.DataFrame(table_t, columns=headers[0][:7])
df_offensive
df_offensive = df_offensive.drop('Rating',axis=1)

- Shots pg: Shots per game
- Shots OT pg: Shots on target per game
- Dribbles pg: Dribbles per game
- Fouled pg: Fouled per game

# Selection des Tables Situationelles

## I - Situational Goals

In [147]:
headers, table_t = parse_glob(nb_de_pages,
                              teams=20,
                              parameters=7,
                              table="#stage-goals-grid")

None

In [149]:

df_situational_goals = pd.DataFrame(table_t, columns=headers[0][:7])
df_situational_goals

,R,Team,Open Play,Counter Attack,Set Piece,Penalty,Own Goal
0,1,Manchester City,72,5,11,3,4
1,2,Liverpool,53,6,20,7,3
2,3,Arsenal,49,3,13,4,4
3,4,Chelsea,45,1,10,5,2
4,5,Tottenham,41,5,16,4,1
5,6,Manchester United,40,4,12,9,0
6,7,Watford,35,3,12,1,1
7,8,Everton,33,2,16,2,1
8,9,West Ham,32,3,11,5,1
9,10,Southampton,31,1,8,4,1
10,11,Newcastle United,29,1,10,1,1
11,12,Crystal Palace,28,2,8,10,3
12,13,Bournemouth,26,9,13,7,1
13,14,Burnley,26,1,14,2,2
14,15,Wolverhampton Wanderers,26,5,11,4,1
15,16,Leicester,24,8,11,5,3
16,17,Fulham,24,2,5,2,1
17,18,Cardiff,19,0,11,3,1
18,19,Brighton,12,4,14,5,0
19,20,Huddersfield,10,1,9,1,1

## II - Pass Type

In [151]:
headers, table_t = parse_glob(nb_de_pages,
                              teams=20,
                              parameters=6,
                              table="#stage-passes-grid",
                              button='//*[@id="stage-situation-stats-options"]/li[2]/a')

//*[@id="stage-situation-stats-options"]/li[2]/a

In [152]:
df_situational_pass = pd.DataFrame(table_t, columns=headers[0][:7])
df_situational_pass

,R,Team,Cross pg,Through Ball pg,Long Balls pg,Short Passes pg
0,1,Manchester City,21,3,48,655
1,2,Chelsea,18,4,46,616
2,3,Liverpool,19,3,60,567
3,4,Tottenham,17,2,60,505
4,5,Arsenal,16,2,55,499
5,6,Manchester United,17,2,60,450
6,7,Fulham,16,1,65,406
7,8,Leicester,21,3,62,394
8,9,Everton,22,1,61,377
9,10,Wolverhampton Wanderers,16,1,68,373
10,11,Bournemouth,16,2,52,373
11,12,West Ham,17,2,62,372
12,13,Huddersfield,20,1,69,353
13,14,Watford,15,1,65,346
14,15,Crystal Palace,15,1,60,346
15,16,Southampton,18,1,63,316
16,17,Brighton,17,0,70,306
17,18,Newcastle United,19,1,71,288
18,19,Burnley,18,1,78,269
19,20,Cardiff,15,1,67,204

## III - Attaques Situationnelles

In [153]:
headers, table_t = parse_glob(nb_de_pages,
                              teams=20,
                              parameters=5,
                              table="#stage-touch-channels")

None

In [154]:

df_situational_attack = pd.DataFrame(table_t, columns=headers[0][:5])
df_situational_attack

     R                     Team Left Side Middle of the pitch Right Side
0    1           Crystal Palace       44%                 24%        32%
1    2                  Arsenal       42%                 24%        34%
2    3        Manchester United       42%                 26%        31%
3    4          Manchester City       42%                 26%        33%
4    5              Southampton       41%                 25%        33%
5    6                 Brighton       41%                 21%        38%
6    7                  Burnley       41%                 26%        33%
7    8                Leicester       39%                 25%        36%
8    9         Newcastle United       39%                 24%        37%
9   10                  Chelsea       39%                 27%        35%
10  11                  Everton       39%                 22%        40%
11  12              Bournemouth       38%                 24%        38%
12  13             Huddersfield       37%                 20%        42%
13  14                 West Ham       37%                 23%        39%
14  15                Tottenham       37%                 27%        36%
15  16                   Fulham       37%                 28%        35%
16  17                Liverpool       36%                 27%        37%
17  18  Wolverhampton Wanderers       36%                 22%        42%
18  19                  Cardiff       36%                 26%        38%
19  20                  Watford       35%                 31%        34%

## IV - Directions des Tirs

In [157]:
headers, table_t = parse_glob(nb_de_pages,
                              teams=20,
                              parameters=5,
                              table="#stage-attempt-directions",
                              button='//*[@id="stage-pitch-stats-options"]/li[2]/a')

//*[@id="stage-pitch-stats-options"]/li[2]/a

In [158]:

df_situational_shot_direction = pd.DataFrame(table_t, columns=headers[0][:5])
df_situational_shot_direction

     R                     Team Left Side Attempts from the middle Right Side
0    1           Crystal Palace       25%                      62%        13%
1    2                  Chelsea       24%                      60%        16%
2    3                  Cardiff       22%                      66%        12%
3    4        Manchester United       22%                      67%        11%
4    5                 West Ham       21%                      65%        14%
5    6              Southampton       20%                      66%        14%
6    7                Tottenham       20%                      63%        17%
7    8         Newcastle United       19%                      68%        14%
8    9                  Watford       19%                      69%        11%
9   10              Bournemouth       19%                      69%        12%
10  11          Manchester City       18%                      66%        16%
11  12                  Arsenal       17%                      69%        14%
12  13                  Everton       17%                      66%        17%
13  14                 Brighton       17%                      69%        14%
14  15                   Fulham       17%                      67%        15%
15  16             Huddersfield       17%                      66%        16%
16  17                Leicester       16%                      67%        17%
17  18  Wolverhampton Wanderers       16%                      64%        20%
18  19                Liverpool       14%                      69%        17%
19  20                  Burnley       13%                      77%        10%

## V - Zone des Tirs

In [159]:
headers, table_t = parse_glob(nb_de_pages,
                              teams=20,
                              parameters=5,
                              table="#stage-attempt-zones",
                              button='//*[@id="stage-pitch-stats-options"]/li[3]/a')

//*[@id="stage-pitch-stats-options"]/li[3]/a

In [160]:
df_situational_shot_zones = pd.DataFrame(table_t, columns=headers[0][:5])
df_situational_shot_zones

     R                     Team In 6 Yards Box In 18 Yards Box Outside of Box
0    1                  Burnley            16%             54%            30%
1    2                  Arsenal            10%             57%            33%
2    3                  Cardiff            10%             50%            40%
3    4                 West Ham             9%             54%            37%
4    5                Liverpool             9%             56%            34%
5    6                Tottenham             9%             52%            39%
6    7          Manchester City             9%             57%            35%
7    8                 Brighton             9%             53%            39%
8    9  Wolverhampton Wanderers             8%             54%            38%
9   10        Manchester United             8%             51%            41%
10  11                Leicester             7%             51%            42%
11  12              Southampton             7%             49%            43%
12  13                  Everton             7%             61%            33%
13  14              Bournemouth             7%             58%            34%
14  15                  Chelsea             6%             57%            38%
15  16         Newcastle United             6%             54%            40%
16  17                  Watford             6%             58%            35%
17  18                   Fulham             6%             48%            46%
18  19           Crystal Palace             6%             57%            37%
19  20             Huddersfield             4%             53%            42%

## VI - Zone d'action

In [215]:
headers, table_t = parse_glob(nb_de_pages,
                              teams=20,
                              parameters=5,
                              table="#stage-touch-zones",
                              button='//*[@id="stage-pitch-stats-options"]/li[4]/a')

//*[@id="stage-pitch-stats-options"]/li[4]/a

In [216]:
df_situational_action_zones = pd.DataFrame(table_t, columns=headers[0][:5])
df_situational_action_zones

     R                     Team Own Third Middle Third Opposition Third
0    1              Bournemouth       31%          44%              26%
1    2         Newcastle United       30%          47%              24%
2    3           Crystal Palace       30%          45%              25%
3    4                 Brighton       30%          45%              23%
4    5                  Arsenal       29%          45%              27%
5    6                   Fulham       29%          47%              24%
6    7                  Burnley       29%          45%              27%
7    8                Leicester       28%          46%              27%
8    9                 West Ham       28%          47%              25%
9   10                  Watford       28%          45%              27%
10  11                  Cardiff       28%          44%              28%
11  12              Southampton       27%          46%              28%
12  13                  Everton       27%          44%              30%
13  14  Wolverhampton Wanderers       27%          48%              24%
14  15        Manchester United       27%          46%              27%
15  16                Tottenham       27%          45%              28%
16  17             Huddersfield       26%          46%              27%
17  18                  Chelsea       24%          44%              32%
18  19                Liverpool       23%          47%              31%
19  20          Manchester City       19%          46%              35%

# Combinaison Tables

In [312]:
Dataframe_Manager = []
#Dataframe_Manager.append(df_summary)
Dataframe_Manager.append(df_defensive)
Dataframe_Manager.append(df_offensive)
Dataframe_Manager.append(df_situational_goals)
Dataframe_Manager.append(df_situational_pass)
Dataframe_Manager.append(df_situational_attack)
Dataframe_Manager.append(df_situational_shot_direction)
Dataframe_Manager.append(df_situational_shot_zones)
Dataframe_Manager.append(df_situational_action_zones)

In [314]:
# Pour ne pas perdre le DataFrame Manager
Dataframe_Manager_Double = Dataframe_Manager.copy()

In [315]:
for i in range(len(Dataframe_Manager_Double)):
    Dataframe_Manager_Double[i] = Dataframe_Manager_Double[i].drop(columns="R")

In [316]:
Dataframe_Manager_Double[-1].columns=['Team','Action in Own Third','Action in Middle Third','Action in Opposition Third']
Dataframe_Manager_Double[-2].columns=['Team','Shot in 6 Yards Box','Shot in 18 Yards Box','Shot outside of Box']
Dataframe_Manager_Double[-3].columns=['Team',"Attemps from left Side","Attempts from the middle","Attemps from right Side"]
Dataframe_Manager_Double[-4].columns=['Team','Attack from left dide','Attack from middle of the pitch','Attack from right side']

In [318]:
dataframe_global= []
dataframe_global = Dataframe_Manager_Double[0]
for i in range(1,len(Dataframe_Manager_Double)):
    dataframe_global = dataframe_global.merge(Dataframe_Manager_Double[i],on='Team')

In [320]:
dataframe_global.columns

Index(['Team', 'Shots conceded pg', 'Tackles pg', 'Interceptions pg',
       'Fouls pg', 'Offsides pg', 'Shots pg', 'Shots OT pg', 'Dribbles pg',
       'Fouled pg', 'Open Play', 'Counter Attack', 'Set Piece', 'Penalty',
       'Own Goal', 'Cross pg', 'Through Ball pg', 'Long Balls pg',
       'Short Passes pg', 'Attack from left dide',
       'Attack from middle of the pitch', 'Attack from right side',
       'Attemps from left Side', 'Attempts from the middle',
       'Attemps from right Side', 'Shot in 6 Yards Box',
       'Shot in 18 Yards Box', 'Shot outside of Box', 'Action in Own Third',
       'Action in Middle Third', 'Action in Opposition Third'],
      dtype='object')

In [321]:
dataframe_global

,Team,Shots conceded pg,Tackles pg,Interceptions pg,Fouls pg,Offsides pg,Shots pg,Shots OT pg,Dribbles pg,Fouled pg,...,Attack from right side,Attemps from left Side,Attempts from the middle,Attemps from right Side,Shot in 6 Yards Box,Shot in 18 Yards Box,Shot outside of Box,Action in Own Third,Action in Middle Third,Action in Opposition Third
0,Manchester City,6.3,13.7,9.5,8.6,2.6,18,6.8,11.5,7.9,...,33%,18%,66%,16%,9%,57%,35%,19%,46%,35%
1,Liverpool,8.1,16.1,8.3,8.3,2,15.1,5.9,9.4,9.1,...,37%,14%,69%,17%,9%,56%,34%,23%,47%,31%
2,Chelsea,9.2,16.3,9.3,8.9,2.2,16,5.2,11.8,11.2,...,35%,24%,60%,16%,6%,57%,38%,24%,44%,32%
3,Tottenham,12.1,16.5,8.6,9.9,1.9,14.1,5,9.7,9.6,...,36%,20%,63%,17%,9%,52%,39%,27%,45%,28%
4,Arsenal,13.1,16,10.8,10.8,2.3,12.3,4.5,8,12,...,34%,17%,69%,14%,10%,57%,33%,29%,45%,27%
5,Leicester,11.2,17.8,11.5,9.2,1.9,13.6,4.8,10.3,9.9,...,36%,16%,67%,17%,7%,51%,42%,28%,46%,27%
6,Crystal Palace,13.8,19.3,11.7,10.2,2.1,13,3.9,9.9,10.3,...,32%,25%,62%,13%,6%,57%,37%,30%,45%,25%
7,West Ham,13.9,19,12,8.7,1.9,11.6,4.1,10.2,10.2,...,39%,21%,65%,14%,9%,54%,37%,28%,47%,25%
8,Everton,10.6,18.4,11.9,11.4,1.8,13.1,4.4,8.7,11,...,40%,17%,66%,17%,7%,61%,33%,27%,44%,30%
9,Wolverhampton Wanderers,12.2,18.9,13.2,10.8,1.9,12.6,4,8.7,8.6,...,42%,16%,64%,20%,8%,54%,38%,27%,48%,24%
10,Newcastle United,12.9,18.8,13.3,11.1,1.6,11.7,3.7,6.2,8.7,...,37%,19%,68%,14%,6%,54%,40%,30%,47%,24%
11,Manchester United,13.1,15.3,9.3,11.4,2.4,13.8,5.9,8.4,10.4,...,31%,22%,67%,11%,8%,51%,41%,27%,46%,27%
12,Burnley,17.2,15.4,9.7,9.5,2.8,9.5,3.1,5.4,9.4,...,33%,13%,77%,10%,16%,54%,30%,29%,45%,27%
13,Southampton,13.7,18.4,14.4,11.1,1.6,12.7,4.3,7.6,9,...,33%,20%,66%,14%,7%,49%,43%,27%,46%,28%
14,Watford,12.9,17.3,11.3,11.4,2.3,11.5,4,7.7,10.1,...,34%,19%,69%,11%,6%,58%,35%,28%,45%,27%
15,Bournemouth,13.7,13.8,9.8,8.9,1.5,11.7,4.3,7.7,11.6,...,38%,19%,69%,12%,7%,58%,34%,31%,44%,26%
16,Cardiff,15,17.2,13.9,9.8,2,11,3.3,6.8,10.3,...,38%,22%,66%,12%,10%,50%,40%,28%,44%,28%
17,Brighton,15.3,17.9,12.2,12.2,2.4,9.8,2.8,7.1,7.9,...,38%,17%,69%,14%,9%,53%,39%,30%,45%,23%
18,Fulham,15.4,15.7,11.3,11.1,2.4,11.9,3.8,9.3,9,...,35%,17%,67%,15%,6%,48%,46%,29%,47%,24%
19,Huddersfield,13.7,18.6,14,11.1,1.7,10.6,3.1,6.1,9.7,...,42%,17%,66%,16%,4%,53%,42%,26%,46%,27%

# Automatisation

### Pour 2018-2019 // Automatisation du parcours de ligues

In [352]:
teams_leagues = [20,20,20,18,20]

In [ ]:
DataFrameManager_Manager  = []
RAW_DataFrameManager_Manager = []
for i in range(len(df_url)):
    
    # GETTING THE URL
    url = df_url['2018-2019'][i]
    driver = webdriver.Chrome()
    driver.get(url)
    
    time.sleep(5)
    
    #CLICKING THE PRIVACY POP UP
    button_to_click =driver.find_elements_by_xpath('//*[@id="qcCmpButtons"]/button[2]')[0]
    button_to_click.click()
    
    time.sleep(5)
    

    
    # GETTING AND WRITTING DATA FRAMES
    ## DEFENSIVE
    headers, table_t = parse_glob(nb_de_pages,
                              teams=teams_leagues[i],
                              parameters=8,
                              table="#stage-team-stats-defensive",
                              button='//*[@id="stage-team-stats-options"]/li[2]/a')

    
    df_defensive = pd.DataFrame(table_t, columns=headers[0][:8])
    df_defensive.columns = ['R', 'Team', 'Shots conceded pg', 'Tackles pg', 'Interceptions pg', 'Fouls pg',
       'Offsides pg', 'Rating']
    df_defensive = df_defensive.drop('Rating',axis=1)
    
    

    
    ## OFFENSIVE 
    headers, table_t = parse_glob(nb_de_pages,
                              teams=teams_leagues[i],
                              parameters=7,
                              table="#stage-team-stats-offensive",
                              button='//*[@id="stage-team-stats-options"]/li[3]/a')
    
    df_offensive = pd.DataFrame(table_t, columns=headers[0][:7])
    df_offensive = df_offensive.drop('Rating',axis=1)
    
    
    # SITUATIONAL GOALS
    headers, table_t = parse_glob(nb_de_pages,
                              teams=teams_leagues[i],
                              parameters=7,
                              table="#stage-goals-grid")
    df_situational_goals = pd.DataFrame(table_t, columns=headers[0][:7])
    
    # SITUATIONAL PASS
    headers, table_t = parse_glob(nb_de_pages,
                              teams=20,
                              parameters=6,
                              table="#stage-passes-grid",
                              button='//*[@id="stage-situation-stats-options"]/li[2]/a')
    df_situational_pass = pd.DataFrame(table_t, columns=headers[0][:7])
    
    # SITUATIONAL ATTACKS
    headers, table_t = parse_glob(nb_de_pages,
                              teams=teams_leagues[i],
                              parameters=5,
                              table="#stage-touch-channels")
    df_situational_attack = pd.DataFrame(table_t, columns=headers[0][:5])
    
    # Situational SHOTS DIRECTION
    headers, table_t = parse_glob(nb_de_pages,
                              teams=teams_leagues[i],
                              parameters=5,
                              table="#stage-attempt-directions",
                              button='//*[@id="stage-pitch-stats-options"]/li[2]/a')
    df_situational_shot_direction = pd.DataFrame(table_t, columns=headers[0][:5])
    
    # SITUATIONAL SHOT ZONES
    
    headers, table_t = parse_glob(nb_de_pages,
                              teams=teams_leagues[i],
                              parameters=5,
                              table="#stage-attempt-zones",
                              button='//*[@id="stage-pitch-stats-options"]/li[3]/a')
    df_situational_shot_zones = pd.DataFrame(table_t, columns=headers[0][:5])
    
    # SITUATION ACTION ZONES
    
    headers, table_t = parse_glob(nb_de_pages,
                              teams=20,
                              parameters=5,
                              table="#stage-touch-zones",
                              button='//*[@id="stage-pitch-stats-options"]/li[4]/a')
    df_situational_action_zones = pd.DataFrame(table_t, columns=headers[0][:5])
    
    #print(df_offensive)
    
    Dataframe_Manager = []
    Dataframe_Manager.append(df_defensive)
    Dataframe_Manager.append(df_offensive)
    Dataframe_Manager.append(df_situational_goals)
    Dataframe_Manager.append(df_situational_pass)
    Dataframe_Manager.append(df_situational_attack)
    Dataframe_Manager.append(df_situational_shot_direction)
    Dataframe_Manager.append(df_situational_shot_zones)
    Dataframe_Manager.append(df_situational_action_zones)
    
    RAW_DataFrameManager_Manager.append(Dataframe_Manager)
    
    for i in range(len(Dataframe_Manager)):
        Dataframe_Manager[i] = Dataframe_Manager[i].drop(columns="R")
    
    Dataframe_Manager[-1].columns=['Team','Action in Own Third','Action in Middle Third','Action in Opposition Third']
    Dataframe_Manager[-2].columns=['Team','Shot in 6 Yards Box','Shot in 18 Yards Box','Shot outside of Box']
    Dataframe_Manager[-3].columns=['Team',"Attemps from left Side","Attempts from the middle","Attemps from right Side"]
    Dataframe_Manager[-4].columns=['Team','Attack from left dide','Attack from middle of the pitch','Attack from right side']
    
    dataframe_global= []
    dataframe_global = Dataframe_Manager[0]
    for i in range(1,len(Dataframe_Manager)):
        dataframe_global = dataframe_global.merge(Dataframe_Manager[i],on='Team')
        
    DataFrameManager_Manager.append(dataframe_global)
    
    driver.close()
    
    #DATAFRAMES
    del df_defensive
    del df_offensive
    del df_situational_goals
    del df_situational_pass
    del df_situational_attack
    del df_situational_shot_direction
    del df_situational_shot_zones
    del df_situational_action_zones

In [384]:
DataFrameManager_Manager[-1]

,Team,Shots conceded pg,Tackles pg,Interceptions pg,Fouls pg,Offsides pg,Shots pg,Shots OT pg,Dribbles pg,Fouled pg,...,Attack from right side,Attemps from left Side,Attempts from the middle,Attemps from right Side,Shot in 6 Yards Box,Shot in 18 Yards Box,Shot outside of Box,Action in Own Third,Action in Middle Third,Action in Opposition Third
0,Paris Saint-Germain,10.5,18.4,9,12.5,2.4,14.8,6.1,11.9,11.7,...,33%,21%,63%,17%,9%,61%,29%,22%,47%,31%
1,Lyon,12.6,16.8,9.6,11.7,2.5,17.7,6.6,12.2,12.3,...,37%,24%,60%,16%,7%,54%,39%,24%,47%,28%
2,Lille,9.9,16.5,10.2,12.6,1,13.1,5.1,9.6,13.4,...,42%,16%,65%,19%,4%,53%,43%,25%,48%,27%
3,Montpellier,11.9,20,12.8,14.1,1.5,13.4,4.5,8,12.6,...,40%,17%,62%,20%,6%,49%,44%,26%,47%,27%
4,Saint-Etienne,12.4,17.7,11.6,11.9,1.6,13.1,4.7,8.3,12,...,40%,19%,62%,19%,8%,52%,40%,28%,46%,26%
5,Marseille,10.5,20.5,10.6,13.2,1.2,13.9,4.5,9.4,12,...,44%,15%,69%,16%,7%,55%,37%,25%,47%,28%
6,Nice,13.1,17.4,11.8,11.2,1.1,11.6,3.4,13.3,13.6,...,36%,20%,63%,17%,6%,49%,45%,30%,46%,23%
7,Nimes,12.8,19.3,11.7,12.8,1.1,13.7,4.7,9.6,13,...,42%,24%,55%,21%,8%,48%,44%,26%,45%,28%
8,Strasbourg,13.1,17.1,11.3,13.5,1.1,10.6,4.1,7.5,10.6,...,42%,14%,67%,18%,5%,53%,42%,27%,47%,26%
9,Rennes,12.6,17.2,10.2,12.9,1.6,12.4,4.2,10.3,12.8,...,41%,21%,58%,21%,9%,47%,44%,27%,47%,27%
10,Reims,11.8,20,12.8,14,2.1,10.7,3.6,8.4,12.3,...,37%,24%,59%,17%,5%,56%,39%,30%,46%,25%
11,Nantes,10.7,20.2,11.4,13,2,13.6,3.9,7.4,13.1,...,37%,17%,66%,16%,5%,47%,48%,26%,46%,28%
12,Angers,12.1,17.7,11.1,11.8,1.3,11.9,4.1,8.3,11.7,...,36%,23%,63%,14%,8%,53%,39%,27%,49%,25%
13,Bordeaux,13.1,18.9,10.3,14.3,1.6,11.2,3.6,9.1,13.1,...,38%,19%,64%,17%,5%,45%,50%,29%,48%,25%
14,Toulouse,15,17.6,10.1,14.7,1.8,11.4,3.5,9.6,12.3,...,35%,18%,68%,15%,5%,56%,39%,28%,45%,26%
15,Monaco,11.3,18.1,10.2,13.9,1.4,12.3,4.2,7.7,13.3,...,40%,16%,66%,18%,5%,55%,40%,26%,46%,28%
16,Caen,14.3,18.7,12.9,14.7,1.3,8.8,2.6,7.1,13.2,...,39%,20%,66%,14%,6%,48%,46%,28%,48%,23%
17,Dijon,14.3,17.7,12.7,15.1,1.6,12,3.8,9.2,11.7,...,35%,19%,65%,17%,4%,49%,48%,27%,46%,28%
18,Amiens,13.2,16.6,10.3,13.7,1.7,10.2,3.1,6.7,13.7,...,35%,22%,59%,19%,4%,47%,49%,27%,47%,26%
19,Guingamp,12.3,18,11,12.8,1.4,10.9,3,9.3,12.2,...,37%,20%,61%,19%,5%,52%,43%,25%,47%,28%

## Automatisation par année

In [388]:
years = ['2018-2019','2017-2018','2016-2017']

In [ ]:
Final_DataFrame_Manager = []
for j in range(len(years)):
    DataFrameManager_Manager  = []
    for i in range(len(df_url)):
    
        # GETTING THE URL
        url = df_url[years[j]][i]
        driver = webdriver.Chrome()
        driver.get(url)
    
        time.sleep(5)
    
        #CLICKING THE PRIVACY POP UP
        button_to_click =driver.find_elements_by_xpath('//*[@id="qcCmpButtons"]/button[2]')[0]
        button_to_click.click()
    
        time.sleep(5)
    

    
        # GETTING AND WRITTING DATA FRAMES
        ## DEFENSIVE
        headers, table_t = parse_glob(nb_de_pages,
                              teams=teams_leagues[i],
                              parameters=8,
                              table="#stage-team-stats-defensive",
                              button='//*[@id="stage-team-stats-options"]/li[2]/a')

    
        df_defensive = pd.DataFrame(table_t, columns=headers[0][:8])
        df_defensive.columns = ['R', 'Team', 'Shots conceded pg', 'Tackles pg', 'Interceptions pg', 'Fouls pg',
           'Offsides pg', 'Rating']
        df_defensive = df_defensive.drop('Rating',axis=1)
    
    

    
        ## OFFENSIVE 
        headers, table_t = parse_glob(nb_de_pages,
                              teams=teams_leagues[i],
                              parameters=7,
                              table="#stage-team-stats-offensive",
                              button='//*[@id="stage-team-stats-options"]/li[3]/a')
    
        df_offensive = pd.DataFrame(table_t, columns=headers[0][:7])
        df_offensive = df_offensive.drop('Rating',axis=1)
    
    
        # SITUATIONAL GOALS
        headers, table_t = parse_glob(nb_de_pages,
                              teams=teams_leagues[i],
                              parameters=7,
                              table="#stage-goals-grid")
        df_situational_goals = pd.DataFrame(table_t, columns=headers[0][:7])
    
        # SITUATIONAL PASS
        headers, table_t = parse_glob(nb_de_pages,
                              teams=20,
                              parameters=6,
                              table="#stage-passes-grid",
                              button='//*[@id="stage-situation-stats-options"]/li[2]/a')
        df_situational_pass = pd.DataFrame(table_t, columns=headers[0][:7])
    
        # SITUATIONAL ATTACKS
        headers, table_t = parse_glob(nb_de_pages,
                              teams=teams_leagues[i],
                              parameters=5,
                              table="#stage-touch-channels")
        df_situational_attack = pd.DataFrame(table_t, columns=headers[0][:5])
    
        # Situational SHOTS DIRECTION
        headers, table_t = parse_glob(nb_de_pages,
                              teams=teams_leagues[i],
                              parameters=5,
                              table="#stage-attempt-directions",
                              button='//*[@id="stage-pitch-stats-options"]/li[2]/a')
        df_situational_shot_direction = pd.DataFrame(table_t, columns=headers[0][:5])
    
        # SITUATIONAL SHOT ZONES
    
        headers, table_t = parse_glob(nb_de_pages,
                              teams=teams_leagues[i],
                              parameters=5,
                              table="#stage-attempt-zones",
                              button='//*[@id="stage-pitch-stats-options"]/li[3]/a')
        df_situational_shot_zones = pd.DataFrame(table_t, columns=headers[0][:5])
    
        # SITUATION ACTION ZONES
    
        headers, table_t = parse_glob(nb_de_pages,
                              teams=20,
                              parameters=5,
                              table="#stage-touch-zones",
                              button='//*[@id="stage-pitch-stats-options"]/li[4]/a')
        df_situational_action_zones = pd.DataFrame(table_t, columns=headers[0][:5])
    
        #print(df_offensive)
    
        Dataframe_Manager = []
        Dataframe_Manager.append(df_defensive)
        Dataframe_Manager.append(df_offensive)
        Dataframe_Manager.append(df_situational_goals)
        Dataframe_Manager.append(df_situational_pass)
        Dataframe_Manager.append(df_situational_attack)
        Dataframe_Manager.append(df_situational_shot_direction)
        Dataframe_Manager.append(df_situational_shot_zones)
        Dataframe_Manager.append(df_situational_action_zones)
    
    
        for i in range(len(Dataframe_Manager)):
            Dataframe_Manager[i] = Dataframe_Manager[i].drop(columns="R")
    
        Dataframe_Manager[-1].columns=['Team','Action in Own Third','Action in Middle Third','Action in Opposition Third']
        Dataframe_Manager[-2].columns=['Team','Shot in 6 Yards Box','Shot in 18 Yards Box','Shot outside of Box']
        Dataframe_Manager[-3].columns=['Team',"Attemps from left Side","Attempts from the middle","Attemps from right Side"]
        Dataframe_Manager[-4].columns=['Team','Attack from left dide','Attack from middle of the pitch','Attack from right side']
    
        dataframe_global= []
        dataframe_global = Dataframe_Manager[0]
        for i in range(1,len(Dataframe_Manager)):
            dataframe_global = dataframe_global.merge(Dataframe_Manager[i],on='Team')
        
        DataFrameManager_Manager.append(dataframe_global)
    
        driver.close()
    
        #DATAFRAMES
        del df_defensive
        del df_offensive
        del df_situational_goals
        del df_situational_pass
        del df_situational_attack
        del df_situational_shot_direction
        del df_situational_shot_zones
        del df_situational_action_zones
    
    Final_DataFrame_Manager.append(DataFrameManager_Manager)

# Ecriture

In [395]:
for i in range(len(years)):
    for j in range(len(League)):
        df = Final_DataFrame_Manager[i][j]
        df.to_csv("Team_Stats_"+str(years[i])+"_"+str(League[j])+".csv")

IndexError: list index out of range